version: "3"
services:
  boldo-web:
    stdin_open: true
    tty: true
    container_name: boldo
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/app/src
    environment:
      - REACT_APP_SOCKETS_ADDRESS=http://localhost:8000
      - REACT_APP_SERVER_ADDRESS=http://localhost:8008
    networks:
      - boldo-network-lite
    #env_file:
    #  - ./.env
networks:
  boldo-network-lite:
    external: true
    